#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    VIM_MARK = SAFE_RANGE,
    VIM_GOTOMARK
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_60_ansi(KC_LGUI, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC,
                             KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, 
                             KC_GESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, 
                             KC_LSPO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSPC, 
                             KC_LCTL, MO(1), KC_LALT, KC_SPC, MO(1), KC_RALT, KC_RGUI, KC_RCTL),
        [1] = LAYOUT_60_ansi(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_DEL, 
                             KC_NO, RGB_TOG, RGB_MOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, KC_NO, KC_NO, KC_NO, KC_NO, RESET, 
                             KC_GRV, KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_MPLY, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, 
                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, VIM_MARK, VIM_GOTOMARK, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO)
};

enum combo_events {
  OP_CHANGETAB,
  JK_BACKSPACE
};


const uint16_t PROGMEM tab_combo[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM backspace_combo[] = {KC_J, KC_K, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {
  [OP_CHANGETAB] = COMBO_ACTION(tab_combo),
  [JK_BACKSPACE] = COMBO_ACTION(backspace_combo),
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case VIM_MARK:
        if (record->event.pressed) {
          tap_code(KC_M);
          register_code(KC_LSHIFT);
          tap_code(KC_A);
          unregister_code(KC_LSHIFT);
        }         
        break;
    case VIM_GOTOMARK:
        if (record->event.pressed) {
          tap_code(KC_GRAVE);
          register_code(KC_LSHIFT);
          tap_code(KC_A);
          unregister_code(KC_LSHIFT);
        }         
        break;
    }
    return true;
};

void process_combo_event(uint8_t combo_index, bool pressed) {
  switch(combo_index) {
    case OP_CHANGETAB:
      if (pressed) {
        tap_code16(LALT(KC_TAB));
      }
      break;
    case JK_BACKSPACE:
      if(pressed){
        tap_code(KC_BSPC);
      }
      break;
  }
}


